// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7LsFJC6RN8yB2MyumJK6l5VcwL5gBGg0',
    appId: '1:612874586970:web:960f49771d0b1817084163',
    messagingSenderId: '612874586970',
    projectId: 'smart-kirana-962e3',
    authDomain: 'smart-kirana-962e3.firebaseapp.com',
    storageBucket: 'smart-kirana-962e3.firebasestorage.app',
    measurementId: 'G-P92CB9HV7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmufVRRSAdKffpgvv_Ow6PO-N7DWQRe3I',
    appId: '1:612874586970:android:afc1286208fab505084163',
    messagingSenderId: '612874586970',
    projectId: 'smart-kirana-962e3',
    storageBucket: 'smart-kirana-962e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOYZA5Rx2EHe1j5RnZPhloBbZ53redxh0',
    appId: '1:612874586970:ios:6910da988edcd95a084163',
    messagingSenderId: '612874586970',
    projectId: 'smart-kirana-962e3',
    storageBucket: 'smart-kirana-962e3.firebasestorage.app',
    iosBundleId: 'com.example.smartKiranaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOYZA5Rx2EHe1j5RnZPhloBbZ53redxh0',
    appId: '1:612874586970:ios:6910da988edcd95a084163',
    messagingSenderId: '612874586970',
    projectId: 'smart-kirana-962e3',
    storageBucket: 'smart-kirana-962e3.firebasestorage.app',
    iosBundleId: 'com.example.smartKiranaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7LsFJC6RN8yB2MyumJK6l5VcwL5gBGg0',
    appId: '1:612874586970:web:e07f959bb72d946c084163',
    messagingSenderId: '612874586970',
    projectId: 'smart-kirana-962e3',
    authDomain: 'smart-kirana-962e3.firebaseapp.com',
    storageBucket: 'smart-kirana-962e3.firebasestorage.app',
    measurementId: 'G-F23SPBLCHV',
  );
}
